{
 "title": "Alluxio Demo Summary View Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "alluxio_datasource",
    "label": "The datasource of alluxio prometheus",
    "query": "prometheus"
   },
   {
    "name": "masters",
    "label": "The prometheus job_name including master nodes",
    "query": "alluxio master"
   },
   {
    "name": "workers",
    "label": "The prometheus job_name including worker nodes",
    "query": "alluxio worker"
   },
   { "name": "alluxio_user", "label": "The super user of alluxio", "query": "alluxio" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(Cluster_CacheHitRate{job=\"alluxio_masters\"}*100)"
    }
   ]
  },
  {
   "title": "Cluster Listings Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "Master_ListingCacheHits{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Bytes Read (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(Cluster_BytesReadRemote{job=\"alluxio_masters\"}[1m])",
     "legendFormat": "Bytes Read Remote (Per Minute)"
    }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_BytesReadRemote{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Bytes Read UFS (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(Cluster_BytesReadUfsAll{job=\"alluxio_masters\"}[1m])",
     "legendFormat": "Bytes Read UFS (Per Minute)"
    }
   ]
  },
  {
   "title": "Live Workers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Cluster_Workers{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Bytes Written (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(Cluster_BytesWrittenRemote{job=\"alluxio_masters\"}[1m])",
     "legendFormat": "Bytes Written Remote (Per Minute)"
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_BytesWrittenRemote{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "% Alluxio Cache Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(Cluster_CapacityUsed{job=\"alluxio_masters\"}) / Cluster_CapacityTotal{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Alluxio Cache Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_CapacityUsed{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Worker Cache Space Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"Worker_CapacityTotal_.*\",job=\"alluxio_workers\"}"
    },
    {
     "expr": "{__name__=~\"Worker_CapacityUsed_.*\",job=\"alluxio_workers\"}"
    }
   ]
  },
  {
   "title": "Worker Cached Blocks ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlocksCached.*\",job=\"alluxio_workers\"}"
    }
   ]
  },
  {
   "title": "UFS Space Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_RootUfsCapacityTotal{job=\"alluxio_workers\"}"
    },
    {
     "expr": "Cluster_RootUfsCapacityUsed{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Evicted Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlocksEvicted.*\",job=\"alluxio_workers\"}"
    }
   ]
  },
  {
   "title": "Logical Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Directories Created",
   "type": "stat",
   "description": "Displays the current number of how many directories Alluxio has created since starting",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_DirectoriesCreated{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "File Infos Got",
   "type": "stat",
   "description": "displays the number of times the FileInfosGot operation was called",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_FileInfosGot{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Total Paths",
   "type": "stat",
   "description": "Displays the total paths located in the Alluxio file system",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_TotalPaths{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Complete File Operations",
   "type": "stat",
   "description": "Displays how many times the CompleteFile operation has been called",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_CompleteFileOps{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Create Directory Oprtations",
   "type": "stat",
   "description": "Displays the amount of directories that Alluxio has created (Not the current amount of directories)",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_CreateDirectoryOps{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Delete Path Operations",
   "type": "stat",
   "description": "Displays how many times the deletePath operation has been called (And how many total paths have been deleted)",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_DeletePathOps{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Files Pinned",
   "type": "stat",
   "description": "Displays the current number of pinned files in Alluxio",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_FilesPinned{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Mount Operations",
   "type": "stat",
   "description": "Displays how many times the mount operation has been called (including failed invocations)",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_MountOps{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Files Freed",
   "type": "stat",
   "description": "Displays the current number of freed files in Alluxio",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_FilesFreed{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Unmount Operations",
   "type": "stat",
   "description": "Displays how many times the unmount operation has been called",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_UnmountOps{job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Alluxio Metadata Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GetStatus Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"Master_GetStatus_User:$alluxio_user\",job=\"alluxio_masters\",quantile=\"0.5\"}"
    },
    {
     "expr": "{__name__=\"Master_GetStatus_User:$alluxio_user\",job=\"alluxio_masters\",quantile=\"0.95\"}"
    },
    {
     "expr": "{__name__=\"Master_GetStatus_User:$alluxio_user\",job=\"alluxio_masters\",quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "ListStatus Operation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 71 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"Master_ListStatus_User:$alluxio_user\",job=\"alluxio_masters\",quantile=\"0.5\"}"
    },
    {
     "expr": "{__name__=\"Master_ListStatus_User:$alluxio_user\",job=\"alluxio_masters\",quantile=\"0.95\"}"
    },
    {
     "expr": "{__name__=\"Master_ListStatus_User:$alluxio_user\",job=\"alluxio_masters\",quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "Get Configuration Operation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 71 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"Master_getConfiguration\",job=\"alluxio_masters\",quantile=\"0.5\"}"
    },
    {
     "expr": "{__name__=\"Master_getConfiguration\",job=\"alluxio_masters\",quantile=\"0.95\"}"
    },
    {
     "expr": "{__name__=\"Master_getConfiguration\",job=\"alluxio_masters\",quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "Block Heartbeat Operation",
   "type": "graph",
   "description": "Displays the 50th, 95th, and 99th percentiles call time for the blockHeartbeat metadata operation.\n\nNote: This is not a graph for the actual Block Heartbeat just how long it took the operation to run",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"Master_blockHeartbeat_User:$alluxio_user\",job=\"alluxio_masters\",quantile=\"0.5\"}"
    },
    {
     "expr": "{__name__=\"Master_blockHeartbeat_User:$alluxio_user\",job=\"alluxio_masters\",quantile=\"0.95\"}"
    },
    {
     "expr": "{__name__=\"Master_blockHeartbeat_User:$alluxio_user\",job=\"alluxio_masters\",quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "Worker Heartbeat Operation",
   "type": "graph",
   "description": "Displays the 50th, 95th, and 99th percentiles call time for the workerHeartbeat metadata operation.\n\nNote: This is not a graph for the actual Worker Heartbeat just how long it took the operation to run",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"Worker_Heartbeat_User:$alluxio_user[a-zA-Z0-9_]+\",job=\"alluxio_workers\",quantile=\"0.5\"}"
    },
    {
     "expr": "{__name__=~\"Worker_Heartbeat_User:$alluxio_user[a-zA-Z0-9_]+\",job=\"alluxio_workers\",quantile=\"0.95\"}"
    },
    {
     "expr": "{__name__=~\"Worker_Heartbeat_User:$alluxio_user[a-zA-Z0-9_]+\",job=\"alluxio_workers\",quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "AsyncCache Blocks & Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  },
  {
   "title": "AsyncCacheSuccessedBlocks (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase({__name__=~\"Worker_AsyncCacheSucceededBlocks.*\",job=\"alluxio_workers\"}[1m])"
    }
   ]
  },
  {
   "title": "AsyncCacheFailedBlocks (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase({__name__=~\"Worker_AsyncCacheFailedBlocks.*\",job=\"alluxio_workers\"}[1m])"
    }
   ]
  },
  {
   "title": "AsyncCacheRemoteBlocks (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase({__name__=~\"Worker_AsyncCacheRemoteBlocks.*\",job=\"alluxio_workers\"}[1m])"
    }
   ]
  },
  {
   "title": "AsyncCacheUfsBlocks (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase({__name__=~\"Worker_AsyncCacheUfsBlocks.*\",job=\"alluxio_workers\"}[1m])"
    }
   ]
  },
  {
   "title": "AsyncCacheRequests (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase({__name__=~\"Worker_AsyncCacheRequests.*\",job=\"alluxio_workers\"}[1m])"
    }
   ]
  },
  {
   "title": "AsyncCacheDuplicateRequests (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase({__name__=~\"Worker_AsyncCacheDuplicateRequests.*\",job=\"alluxio_workers\"}[1m])"
    }
   ]
  },
  {
   "title": "Master JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Master Pools Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"pools_Compressed_Class_Space_used\", job=\"alluxio_masters\"}"
    },
    {
     "expr": "{__name__=\"pools_Metaspace_used\", job=\"alluxio_masters\"}"
    },
    {
     "expr": "{__name__=\"pools_PS_Eden_Space_used\", job=\"alluxio_masters\"}"
    },
    {
     "expr": "{__name__=\"pools_PS_Survivor_Space_used\", job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Master Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 94 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"heap_used\",job=\"alluxio_masters\"}"
    },
    {
     "expr": "{__name__=\"heap_max\",job=\"alluxio_masters\"}"
    },
    {
     "expr": "{__name__=\"non_heap_used\",job=\"alluxio_masters\"}"
    }
   ]
  },
  {
   "title": "Master Total Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 94 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"total_max\",job=\"alluxio_masters\"}"
    },
    {
     "expr": "{__name__=\"total_used\",job=\"alluxio_masters\"}"
    }
   ]
  }
 ]
}